package model.services;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Mar 14 16:19:51 BDT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    /**
     * Container's getter for MainView1.
     * @return MainView1
     */
    public ViewObjectImpl getMainView1() {
        return (ViewObjectImpl)findViewObject("MainView1");
    }

    /**
     * Container's getter for SearchVO1.
     * @return SearchVO1
     */
    public ViewObjectImpl getSearchVO1() {
        return (ViewObjectImpl)findViewObject("SearchVO1");
    }
}
